version: '3'

services:
    web:
        image: g3tech
        container_name: g3tech
        environment:
            - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
            - THINGIVERSE_API_TOKEN=${THINGIVERSE_API_TOKEN}
        ports:
            - 1000:80
